version: '3.3'

services:
  server:
    build:
      context: .
    ports:
      - "5000:5000"
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
